node_id ${REPMGR_NODE_ID}
node_name ${REPMGR_NODE_NAME}
conninfo 'host=${NODE_DOMAIN} port=${POSTGRES_PORT} user=${REPMGR_USER} dbname=${POSTGRES_DB} connect_timeout=5'
data_directory '${PGDATA}'
log_file '${REPMGR_LOG_FILE}'
upstream_node_id ${REPMGR_UPSTREAM_NODE_ID}

use_replication_slots yes
reconnect_attempts 5
reconnect_interval 5
connection_check_type ping

failover automatic
monitoring_history yes
monitoring_interval 5
promote_check_timeout 30
priority ${REPMGR_PRIORITY}

promote_command 'repmgr -f /var/lib/postgresql/repmgr.conf standby promote'
follow_command 'repmgr -f /var/lib/postgresql/repmgr.conf standby follow -W --upstream-node-id=%n'
